/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace SharpLLVM {

public enum AtomicOrdering {
  AtomicOrderingNotAtomic = 0,
  AtomicOrderingUnordered = 1,
  AtomicOrderingMonotonic = 2,
  AtomicOrderingAcquire = 4,
  AtomicOrderingRelease = 5,
  AtomicOrderingAcquireRelease = 6,
  AtomicOrderingSequentiallyConsistent = 7
}

}
