/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace SharpLLVM {

public enum CallConv {
  CCallConv = 0,
  FastCallConv = 8,
  ColdCallConv = 9,
  WebKitJSCallConv = 12,
  AnyRegCallConv = 13,
  X86StdcallCallConv = 64,
  X86FastcallCallConv = 65
}

}
