/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace SharpLLVM {

public enum IntPredicate {
  IntEQ = 32,
  IntNE,
  IntUGT,
  IntUGE,
  IntULT,
  IntULE,
  IntSGT,
  IntSGE,
  IntSLT,
  IntSLE
}

}
