/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace SharpLLVM {

public enum TypeKind {
  VoidTypeKind,
  HalfTypeKind,
  FloatTypeKind,
  DoubleTypeKind,
  X86_FP80TypeKind,
  FP128TypeKind,
  PPC_FP128TypeKind,
  LabelTypeKind,
  IntegerTypeKind,
  FunctionTypeKind,
  StructTypeKind,
  ArrayTypeKind,
  PointerTypeKind,
  VectorTypeKind,
  MetadataTypeKind,
  X86_MMXTypeKind
}

}
